### ISSUE TITLE
Latex Error: Option clash for package hyperref

### ISSUE THREAD

**Issue by JiyangZhang** [pengyunie/latex-template#2]
I come across the following errors while compiling (run command: `make`):

>  ! LaTeX Error: Option clash for package hyperref.
> 
> See the LaTeX manual or LaTeX Companion for explanation.
> Type  H <return>  for immediate help.
>  ...                                              
>                                                   
> l.19 \usepackage
>                 {breakurl}

What I did to avoid the error is commenting out this line [https://github.com/pengyunie/latex-template/blob/46f69c1998ff5762596c0df3163a1320f8988522/macros.tex#L17](https://github.com/pengyunie/latex-template/blob/46f69c1998ff5762596c0df3163a1320f8988522/macros.tex#L17)

Is there anything I missed here?

**Comment by pengyunie** [comment]
Fixed in f8403fbfb7183908689a6f85438be418d6cf90db. Thanks for reporting!
